### GET token from Auth0

curl --request POST \
  --url https://dev-36jwnfzplm68toi0.us.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"lwfIDYCIjc52hUf1iW2nIJrWkT9lsikt","client_secret":"IjOczl1Lv3OI0KPGReFr5je9PIpYKu8MneTlKs2kpZKQx7HbYz0AiltaM3OKvxes","audience":"https://White-Viper-Digit","grant_type":"client_credentials"}'

### DELETE a Item to the Catalog collection

curl --request DELETE \
  --url http://path_to_your_api/ \
  --header 'authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZ6VEhVZ3Y5Uy16eWxabUw1SnlNciJ9.eyJpc3MiOiJodHRwczovL2Rldi0zNmp3bmZ6cGxtNjh0b2kwLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJsd2ZJRFlDSWpjNTJoVWYxaVcybklKcldrVDlsc2lrdEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9XaGl0ZS1WaXBlci1EaWdpdCIsImlhdCI6MTY4Mjc4ODQwNiwiZXhwIjoxNjgyODc0ODA2LCJhenAiOiJsd2ZJRFlDSWpjNTJoVWYxaVcybklKcldrVDlsc2lrdCIsInNjb3BlIjoiZGVsZXRlOmNhdGFsb2ciLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.hUkK3-MIcEvZQdkeoZACNdpJ0jJqNdLszjvp5ob--6-1JRfcEiMJy8QjGGt8OYKSV9hk_sup7uU-_RWBC-OjY0iF5GID1ronpwXYqByFpviOD_f-wQzCtHSJM7x_BEaAdex6mxG5x_s8CJng2QMHxO0P1RhfkuA9dBqc9F2_XS_ECfvka2buxN0hYM3bQ4PAetSSMF_nYDNjHY0hXQ1eJHcra_wEPmakx0JzTvQaqw4KdebmtPp0oJDG0seCM_vdY0ynSl6REOzbb015vYxfCMQ7-kbOq1fCJ5FzzCaYOMZP-51tykfc7WnoQb4fj5sIeFMgetrHyqZXAHeIGUCmAw'
